### ISSUE TITLE
Missing some specific conditions

### ISSUE THREAD

**Issue by Gusarich** [housingdevs/housing-actions#2]
Event conditions are missing. When you are adding some event action, you may have additional conditions available depending on the event. For example, for “player block break” you have “block type” condition.

Currently there are only default conditions in this repo.

**Comment by Gusarich** [comment]
I’m sure we need not only the type definitions for all actions/conditions, but also a list of available special conditions (and actions, if any) for each event type.

**Comment by ixnoahlive** [comment]
Event conditions should have been merged a while back, if not then I will look into that once I am home. I do recall working on those a while back.

**Comment by Gusarich** [comment]
>  but also a list of available special conditions (and actions, if any) for each event type.

actually I just found the `eventActions.json` file

**Comment by ixnoahlive** [comment]
Solved, I believe? Closing for now.
